### ISSUE TITLE
Roadmap for v0.3.0

### ISSUE THREAD

**Issue by jinh0** [jinh0/eyeliner.nvim#22]
- [x] Fix operator pending mode, see #16.
- [x] Repeat "f" functionality like [clever-f.vim](https://github.com/rhysd/clever-f.vim), see https://github.com/jinh0/eyeliner.nvim/issues/11 .
- [x] Option to "dim" all other characters when highlight_on_key mode
- [x] Use `pcall` for enable / disable so as not to break somebody's configuration just because eyeliner is not working

**Comment by jinh0** [comment]
All implemented!
